SRC     = $(shell ls src/*.cpp && ls src/wsq/*.cpp && ls src/features/*.cpp && ls src/prediction/*.cpp)
TARGET  = NFIQ2
INCLUDE = -Iinclude -I. -Iinclude/wsq -Iinclude/features -Iinclude/prediction
PROJECT_ROOT = ..

include $(PROJECT_ROOT)/Makefile.incl

